version: '2'

services:
  nginx_webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql_php
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./ssl:/opt/ssl
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    # volumes_from:
    #   - code_php
  php:
    image: quocsonpham/php7.3-fpm-alpine:0.0.2
    working_dir: /var/www
    # environment:
    #   XDEBUG_CONFIG: "remote_host=10.254.254.254;idekey=PHPSTORM"
    # volumes_from:
    #   - code_php
  mysql_php:
    image: mysql:5.7.28
    ports:
     - "3306:3306"
    volumes:
     - 'mysql_php_data:/var/lib/mysql'
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
  # code_php:
  #   image: busybox
  #   container_name: code
  #   volumes:
  #     - ./www:/var/www

volumes:
  mysql_php_data:
    driver: local
